# Generated by Django 5.2.11 on 2026-03-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
